version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - 'maintenance'
      - 'dependencies'
    reviewers:
      - '@mozilla/fxa-devs'
