parserOptions:
  ecmaVersion: 2017
  sourceType: module
env:
  browser: true
  node: false

globals:
  module: true

plugins:
  - sorting

rules:
  brace-style: 2
  handle-callback-err: 0
  indent: ["error", 2, { "SwitchCase": 1 }]
  key-spacing: [2, {"beforeColon": false, "afterColon": true}]
  keyword-spacing: 2
  linebreak-style: [2, "unix"]
  max-len: [2, 160]
  new-cap: [2, {"newIsCap": true, "capIsNew": false, "newIsCapExceptionPattern": "^FxaClient" }]
  no-console: 0
  no-multi-str: 2
  no-useless-escape: 0
  no-use-before-define: ["error", { classes: false }]
  sorting/sort-object-props: [ 2, { "ignoreCase": true, "ignoreMethods": true, "ignoreObjectsWithMethods": true, "ignorePrivate": true } ]
  space-infix-ops: 2
  space-unary-ops: [2, {"nonwords": false, "overrides": {"~": true, "!": true}}]
  strict: 0
