version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.5.2

jobs:
  testo:
    docker:
      - image: cimg/node:10.23.0-browsers
    steps:
      - checkout
      - browser-tools/install-firefox
      - run: npm install
      - run:
          command: |
            FIREFOX_BIN=/usr/local/bin/firefox npm test
      - store_artifacts:
          path: ./coverage/

workflows:
  version: 2
  build-test:
    jobs:
      - testo

  # Since we don't have many PRs to this repo, periodically run
  # the tests to see if they're still working with the latest
  # versions of nodejs and Firefox.
  periodic-test:
    jobs:
      - testo
    triggers:
      - schedule:
          cron: "5 8 13 * *"
          filters:
            branches:
              only:
                - master


